### ISSUE TITLE
Push to aws failing

### ISSUE THREAD

**Issue by jmorales2718** [gesellix/gradle-docker-plugin#68] opened 2018-06-26 13:33 UTC
Hi  Tobias,
I've read two similar issues [48](https://github.com/gesellix/gradle-docker-plugin/issues/48) and [6](https://github.com/gesellix/gradle-docker-plugin-example/issues/6), but neither really covers what I am working on.

In issue 48, you mentioned that you'd verified pushing to the official registry and localhost, but not private registries found at `some-hostname`. I am currently trying to push to amazon ECR and consistently getting back the error: `request failed: [[errorDetail:[message:denied: requested access to the resource is denied], error:denied: requested access to the resource is denied]]`.  The task is also throwing a `java.lang.IllegalStateException`

I've verified that building images is working fine and that the credentials we need are being pulled down into `.docker/config.json`, but whenever I try to push, I get the above error. I've also verified that I am able to push these images correctly using the standard `docker push` command.

These are the build and push tasks I'm using:

```
task buildFooImage(type: DockerBuildTask, group: "docker-foo"){
    dependsOn "clearFooImage", "jar", "copyDockerfile" //clearFooImage just deletes previous images before building
    imageName = "foo"
    buildContextDirectory = file('build/libs/')
}

task pushToECR(type: DockerPushTask, group: "docker-foo"){
    dependsOn "buildFooImage"
    repositoryName = "foo"
    authConfigPlain = getDockerClient()
            .readAuthConfig("aws_account_id.dkr.ecr.region.amazonaws.com/foo",
                            file("~/.docker/config.json"))
}
```

From what I can tell, it seems like your code is looking for the credentials in the `.docker/config.json` file and using those to push. This behavior makes sense, but I'm not entirely sure. Were you ever able to verify that pushing to private repositories works? What changes would you recommend I look into?

Looking forward to your response,
John

**Comment by gesellix** [comment] 2018-06-26 15:33
Hi John, can try to tag the image first so that it contains the complete repository name? Instead of `foo` you could try `aws_account_id.dkr.ecr.region.amazonaws.com/foo` as `imageName` in your `buildFooImage` task. There's a `DockerTagTask` available, too.

**Comment by jmorales2718** [comment] 2018-06-26 17:59
That seems to have helped because I no longer get the same error. Now I am getting an `no basic auth credentials` error. I am able to successfully login using a bash command, and I've verified that the `.docker/config.json` file contains the correct auth credentials. 

Seems like a common aws error, but with the current login I've got, it works with the [transmode/gradle-docker](https://github.com/Transmode/gradle-docker). We'd much rather use your plugin instead, because you've provided more flexibility with tasks. 

From what I saw in [ManageAuthenticationClient](https://github.com/gesellix/docker-client/blob/master/client/src/main/groovy/de/gesellix/docker/client/authentication/ManageAuthenticationClient.groovy) it seems like you convert from base64 and then parse the user and password from the string.

Any idea why the auth credentials would be effected by this?

**Comment by gesellix** [comment] 2018-06-26 21:12
> verified that the ... file container the correct auth credentials.

I assume you meant that the config file contains the base64 encoded credentials and you haven't found the `credsStore` property. Existing base64 encoded credentials would also imply that they appear under the `aws_account_id.dkr.ecr.region.amazonaws.com` hostname key. Am I correct? I only want to ensure that we're talking about the same config :)

You could help debug the issue by printing the decoded credentials, for example by changing your push task to something like this:

```
task pushToECR(type: DockerPushTask, group: "docker-foo"){
    dependsOn "buildFooImage"
    repositoryName = "foo"
    authConfigPlain = getDockerClient()
            .readAuthConfig("aws_account_id.dkr.ecr.region.amazonaws.com/foo",
                            file("~/.docker/config.json"))
    doFirst {
        logger.lifecycle("auth: ${authConfigPlain}")
    }
}
```

You shouldn't post the result here, please only verify that the output prints your correct credentials for the aws registry. Depending on what we get, we can investigate further.

**Comment by gesellix** [comment] 2018-06-26 21:16
Ah. Wait. I just might have found the issue - is this the real code snippet of your build script?

```
getDockerClient()
            .readAuthConfig("aws_account_id.dkr.ecr.region.amazonaws.com/foo",
                            file("~/.docker/config.json"))
```

The first parameter to `readAuthConfig` should be a hostname and not the image name. So, please ensure that it looks like this:

```
getDockerClient()
            .readAuthConfig("aws_account_id.dkr.ecr.region.amazonaws.com",
                            file("~/.docker/config.json"))
```

And another hint: you can omit the second parameter, because the DockerClient should then try to find the default config file.

**Comment by jmorales2718** [comment] 2018-06-29 15:24
We tried the fix you suspected above and unfortunately it did not work. I'm pretty perplexed as to why this error occurs, but for the time being we have decided to push images with a simple execute shell. So we will not use any plugin to push.

Do you actually need to test this case still or were you just helping me?

**Comment by gesellix** [comment] 2018-06-29 19:33
Did you try to log the credentials and did they look like expected? I would be interested to know whether the decryption of credentials fails or the actual push to the remote registry.

> Do you actually need to test this case still or were you just helping me?

Both ;)

The Gradle plugin (and its underlying Docker client) aim at being a valid and fully compatible alternative to the native Docker client, so I would like to see this issue fixed. I don't have access to AWS ECR, so I cannot test the feature myself. I personally don't _need_ the AWS compatibility, but I would like to know _why_ the simple push task shouldn't work with AWS.

**Comment by gesellix** [comment] 2018-06-29 19:38
leaving a note to myself here:

- https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html
- https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth

**Comment by gesellix** [comment] 2021-04-07 14:48
I can confirm that a push to the AWS ECR works with the config below, given the Docker Engine is logged in. The example pushes to both Docker Hub and AWS ECR.

```shell
# Login to the Docker Hub
docker login --username my-username --password-stdin

# Login to AWS ECR
aws ecr get-login-password | docker login --username AWS --password-stdin my-account-id.dkr.ecr.eu-central-1.amazonaws.com
aws ecr create-repository \
    --repository-name my-repo \
    --region eu-central-1
```

```kotlin
import de.gesellix.docker.client.DockerClient
import de.gesellix.docker.client.authentication.AuthConfig
import de.gesellix.gradle.docker.tasks.DockerBuildTask
import de.gesellix.gradle.docker.tasks.DockerPushTask
import de.gesellix.gradle.docker.tasks.DockerRmiTask

buildscript {
  repositories.addAll(rootProject.buildscript.repositories)
  dependencies {
    classpath("de.gesellix:gradle-docker-plugin:2021-03-01T19-18-38")
  }
}

apply(plugin = "de.gesellix.docker")

val dockerBuildContextSources = file("$projectDir/src/main/docker")
val dockerBuildContextDir = file("$buildDir/docker")
val dockerImageName = "${project.name}"
val dockerImageId = project.provider { "$dockerImageName:${project.version}" }!!

tasks {
  val prepareBuildContext = register<Copy>("prepareBuildContext") {
    from(dockerBuildContextSources)
    into(dockerBuildContextDir)
  }

  val copyArtifact = register<Copy>("copyArtifact") {
    dependsOn(get("bootJar"))
    dependsOn(prepareBuildContext)
    from(get("bootJar"))
    into(dockerBuildContextDir)
    rename { "application.jar" }
  }

  val buildImage = register<DockerBuildTask>("buildImage") {
    dependsOn(copyArtifact)
    setBuildContextDirectory(dockerBuildContextDir)
    imageName = dockerImageId.get()
    buildParams = mapOf("rm" to true, "pull" to true)
    enableBuildLog = true

    doLast {
      logger.info("Image built as $imageName")
    }
  }

  val rmiLocalImage = register<DockerRmiTask>("rmiLocalImage") {
    imageId = dockerImageId.get()
  }

  val ecrHost = "my-account-id.dkr.ecr.eu-central-1.amazonaws.com"
  val registries = listOf(
    RegistryConfig("hub", "my-org") { docker: DockerClient -> docker.readDefaultAuthConfig() },
    RegistryConfig("ecr", ecrHost) { docker: DockerClient -> docker.readAuthConfig(ecrHost, null) }
  )
  registries.forEach { targetRegistry ->
    val rmiImage = register<DockerRmiTask>("rmi${targetRegistry.name.capitalize()}Image") {
      imageId = "${targetRegistry.registry}/${targetRegistry.repository(dockerImageId.get())}"
    }
    val publishImage = register<DockerPushTask>("publish${targetRegistry.name.capitalize()}Image") {
      dependsOn(buildImage)
      repositoryName = targetRegistry.repository(dockerImageId.get())
      registry = targetRegistry.registry
      authConfigPlain = targetRegistry.auth(dockerClient as DockerClient)
      finalizedBy(rmiImage)
    }
    project.tasks.named(PublishingPlugin.PUBLISH_LIFECYCLE_TASK_NAME) {
      finalizedBy(publishImage)
      finalizedBy(rmiLocalImage)
    }
    rmiLocalImage.get().shouldRunAfter(rmiImage)
  }
}

data class RegistryConfig(
  val name: String,
  val registry: String,
  val auth: (DockerClient) -> AuthConfig
)
```

**Comment by gesellix** [comment] 2021-04-07 14:49
Closing because it works. In case you still have issues, please leave a note here or create a new issue!

**Closed by gesellix** 2021-04-07 14:49 UTC
